[Faucet] Specify an asset (for liquid mode) and an amount (#38)
* Add amount and asset in /faucet

* test faucet without amount

* Readme

* Add sleep time

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -3,12 +3,18 @@
 set -e
 
 case $1 in
-  local) ci="false";;
-  ci) ci="true";;
-  *) echo "Invalid option. Aborting."; exit 1;;
+local) ci="false" ;;
+ci) ci="true" ;;
+*)
+  echo "Specify a valid option via the CI environment variable. Aborting."
+  exit 1
+  ;;
 esac
 
-PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))
+PARENT_PATH=$(dirname $(
+  cd $(dirname $0)
+  pwd -P
+))
 
 pushd $PARENT_PATH
 
